#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

use Goutte\Client;

$name = '元尊';
$author = '天蚕土豆';
$cover = 'cover.jpg';
$next = 'http://www.wangshugu.com/books/76/76314/28933238.html';
$page_counter = 1;

$client = new Client();

try {
    do {
        $crawler = $client->request('GET', $next);

        $title = $crawler->filter('#amain > dl > dd > h1')->text();
        $content = $crawler->filter('#contents')->html();
        $next = $crawler->filter('#footlink')->children('a')->last()->link()->getUri();
        $text = sprintf("<h1>%s</h1>\n\n%s\n\n", $title, $content);

        file_put_contents("resources/$name.html", $text, FILE_APPEND);

        echo "$page_counter - $title\n";

        $page_counter++;
    } while (true);
} catch (\Throwable $th) {

}

echo "Done Crawling ($page_counter)\n\n";

$cmd = "pandoc resources/$name.html -f html -t epub -s -o resources/$name.epub -M title:$name -M author:$author --epub-cover-image=resources/$cover --trace";

passthru($cmd);
